# Diese Datei wurde autogeneriert von Valama 0.1.2. Bitte nicht ändern.
set(project_name "Valama")
set(Valama_VERSION "0.1.2")
set(required_pkgs
"gdk-3.0"
"gdl-3.0"
"gee-1.0"
"gio-2.0"
"glib-2.0"
"gobject-2.0"
"gtk+-3.0"
"gtksourceview-3.0"
"guanako"
"libvala-0.18"
"libxml-2.0"
)
set(srcfiles
"src/args.vala"
"src/build_project.vala"
"src/common.vala"
"src/main.vala"
"src/project.vala"
"src/project_templates.vala"
"src/ui_about_dialog.vala"
"src/ui_breakpoints.vala"
"src/ui_build_output.vala"
"src/ui_create_file_dialog.vala"
"src/ui_create_project_dialog.vala"
"src/ui_elements.vala"
"src/ui_helpers.vala"
"src/ui_main.vala"
"src/ui_missing_package_dialog.vala"
"src/ui_project_browser.vala"
"src/ui_project_dialog.vala"
"src/ui_reports.vala"
"src/ui_symbol_browser.vala"
)
set(vapifiles
"vapi/config.vapi"
)
